import * as AqlConfigs from './aql-configs';
import * as Defects from './defects';
import * as InspectionStandards from './inspection-standards';
import * as IqcInspections from './iqc-inspections';
import * as Materials from './materials';
import * as Menus from './menus';
import * as NonConformings from './non-conformings';
import * as Processes from './processes';
import * as QualityIndicators from './quality-indicators';
import * as QualityInspectionPlans from './quality-inspection-plans';
import * as SamplingSchemes from './sampling-schemes';
import * as Suppliers from './suppliers';
export * from './aql-configs.service';
export * from './defects.service';
export * from './execl.service';
export * from './file.service';
export * from './inspection-standards.service';
export * from './iqc-inspections.service';
export * from './materials.service';
export * from './models';
export * from './non-conformings.service';
export * from './processes.service';
export * from './quality-inspection-plans.service';
export * from './sampling-schemes.service';
export * from './suppliers.service';
export { AqlConfigs, Defects, InspectionStandards, IqcInspections, Materials, Menus, NonConformings, Processes, QualityIndicators, QualityInspectionPlans, SamplingSchemes, Suppliers };
